version: '3'
services:
  web:
    build: ./web
    ports:
     - "5001-5003:80"
    volumes:
     - /root/cache_balancer.v2/web/index.html:/usr/share/nginx/html/index.html
    deploy:
      replicas: 3
  
  app:
    build: ./app
    ports:
      - "5004:80"