- name: Download project in local from github
  hosts: localhost
  tasks:
    - name: Download project
      git:
        repo: https://github.com/j0s0n/cache_balancer.v2.git
        dest: /tmp/cache_balancer.v2
        clone: yes
        update: yes

- name: Pass nginx configuration file to Abigail
  hosts: Abi
  tasks:
    - name: Create project directory
      file:
        path: /root/cache_balancer.v2
        state: directory
    - name: Copy redirect directoy to remote host
      copy:
        src: /tmp/cache_balancer.v2/redirect
        dest: /root/cache_balancer.v2
    - name: Build docker image
      shell: docker build /root/cache_balancer.v2/redirect -t redirect
    - name: Launch container
      shell: docker run -d --name redirect1 -p 80:80 redirect

- name: Pass nginx configuration file to Areoso
  hosts: Areoso
  tasks:
    - name: Create project directory
      file:
        path: /root/cache_balancer.v2
        state: directory
    - name: Copy redirect directoy to remote host
      copy:
        src: /tmp/cache_balancer.v2/cache_balancer
        dest: /root/cache_balancer.v2
    - name: Build docker image
      shell: docker build /root/cache_balancer.v2/cache_balancer -t cache_balancer
    - name: Launch container
      shell: docker run -d --name cache_balancer1 -p 2000:80 cache_balancer

- name: Launch Nginx cache and load balancer with docker compose
  hosts: Esteban
  tasks:
    - name: Create project directory
      file:
        path: /root/cache_balancer.v2
        state: directory
    - name: Copy app directoy to remote host
      copy:
        src: /tmp/cache_balancer.v2/app
        dest: /root/cache_balancer.v2
    - name: Copy web directoy to remote host
      copy:
        src: /tmp/cache_balancer.v2/web
        dest: /root/cache_balancer.v2
    - name: Copy docker-compose file to remote host
      copy:
        src: /tmp/cache_balancer.v2/docker-compose.yaml
        dest: /root/cache_balancer.v2
    - name: Remove existing services
      docker_compose:
        project_src: /root/cache_balancer.v2
        state: absent
    - name: Create and start services
      docker_compose:
        project_src: /root/cache_balancer.v2
      register: output

- name: Remove files from local
  hosts: localhost
  tasks:
    - name: Remove project directory
      file:
        path: /tmp/cache_balancer.v2
        state: absent